server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default-schema: public
  datasource:
    url: jdbc:postgresql://localhost:5432/mytask
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  private-key: ${JWT_PRIVATE_KEY_FILE}
  public-key: ${JWT_PUBLIC_KEY_FILE}

upload:
  image-upload-directory: /images/avatar
  max-image-upload-size: 1048576
